services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./reports:/app/reports

  tests:
    build: .
    command: pytest
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./data:/app/data
      - ./scripts:/app/scripts
